name: flutter_popup
description: The flutter_popup package is a versatile tool for creating customizable popups in Flutter apps. Its highlight feature effectively guides user attention to specific areas
version: 3.3.0
homepage: https://github.com/herowws/flutter_popup

environment:
  sdk: '>=2.17.0 <4.0.0'
 
dependencies:
  flutter:
    sdk: flutter
 
dev_dependencies:
  example:
    path: example
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

 